name: "redwood"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

flags:
  require_generic_test_arguments_property: true

models:
  redwood:
    staging:
      +materialized: view
      +schema: staging
      commission_form:
        +tags: ["staging", "commission_form"]

    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]

    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]